# Generated by Django 6.0.2 on 2026-02-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default_cover.png', null=True, upload_to='covers/'),
        ),
    ]
