# Generated by Django 6.0.2 on 2026-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_likes_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='نام دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
