# Generated by Django 6.0.2 on 2026-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_slug_remove_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
